# Generated by Django 4.2.1 on 2023-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('discord', models.CharField(max_length=30)),
                ('steam', models.URLField()),
                ('total_game', models.IntegerField()),
                ('history_game', models.IntegerField()),
                ('ban', models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1)),
                ('vip', models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1)),
            ],
        ),
    ]
